project:
  type: website
  output-dir: docs # For github

website:
  title: "PRO1036"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: website/cours/cours.qmd
        text: "Cours"
      - href: website/labs/labs.qmd
        text: "Labs"
      - href: website/exercices/exos.qmd
        text: "Exercices"

  sidebar:
    - title: "Home"
      contents:
        - index.qmd
  
  
    - title: "Labs"
      contents:
        - website/labs/labs.qmd
        - section: "Semaine 1"
          contents:
            - website/labs/lab01-hello-world/lab01-hello-world.qmd
      
    - title: "Exercices"
      contents:
        - website/exercices/exos.qmd
        - section: "Semaine 1"
          contents:
            - website/exercices/exo01-pet-names/exo01-pet-names.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


bibliography: website/references.bib
csl: website/apa-fr.csl